name = "BlockTensorFactorization"
uuid = "07b766a1-0096-4e53-b687-1cd07becaccb"
version = "0.4.0"
authors = ["Nicholas <njericha@math.ubc.ca>"]

[workspace]
projects = ["test", "benchmark", "docs"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.12.1"
