name: CI
on:
  push: # see https://github.com/orgs/community/discussions/26276#discussioncomment-4617932
    branches:
      - main
    paths-ignore:
    - README.md
    - .gitignore
    - LICENSE.md
  pull_request:
    branches:
      - main
    paths-ignore:
    - README.md
    - .gitignore
    - LICENSE.md
env:
  JULIA_NUM_THREADS: 2
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1' # Latest stable 1.x release
          # - 'lts' # long-term support release
          # - 'pre' # latest stable prerelease
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        #exclude:
        #  - version: '1'
        #    os: macOS-latest
        build_is_production_build:
          - true
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          BUILD_IS_PRODUCTION_BUILD: ${{ matrix.build_is_production_build }}
        with:
          coverage: false
  tests-with-coverage:
    name: Code Coverage #Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          #- 'lts'
          #- 'pre'
        os:
          - ubuntu-latest
        build_is_production_build:
          - false
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          BUILD_IS_PRODUCTION_BUILD: false
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          #file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false  # or true if you want CI to fail when Codecov fails
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1.12'
      - run: |
          julia --project=docs -e '
            import Pkg;
            Pkg.develop(Pkg.PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: julia --project=docs docs/make.jl #Pkg.add("Documenter"); using Pkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
  benchmark:
    needs: docs # ensures this is run after docs. docs replaces gh-pages branch so this needs to happen after
    name: Run Julia benchmark
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install dependencies
        run: |
          julia --project=benchmark -e '
            import Pkg;
            Pkg.develop(Pkg.PackageSpec(path=pwd()));
            Pkg.instantiate()'
      - name: Run benchmark # import Pkg; Pkg.add("BenchmarkTools") # Pkg.develop(PackageSpec(path=pwd()))
          # julia --project=benchmark -e '
            # using Pkg;
            # Pkg.add("BenchmarkTools");
            # Pkg.develop(PackageSpec(path=pwd()));
            # Pkg.instantiate()'
        run: julia --project=benchmark benchmark/runbenchmarks.jl
      - uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
        # env:
        #   cache-name: cache-artifacts
        # with:
        #   path: ~/.julia/artifacts
        #   key: runner.os−test−env.cache−name−{{ hashFiles('**/Project.toml') }}
        #   restore-keys: |
        #     runner.os−test−
        #     ${{ env.cache-name }}-
        #     ${{ runner.os }}-test-
        #     ${{ runner.os }}-
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          # name: Julia benchmark result
          tool: 'julia'
          output-file-path: output.json #benchmark/
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          #external-data-json-path: ./cache/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: false
          #alert-comment-cc-users: '@ktrz,@findmyway'

      # - name: Store benchmark result - separate results repo
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     name: Julia benchmark result
      #     tool: 'julia'
      #     output-file-path: benchmark/output.json
      #     # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
      #     github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
      #     auto-push: true
      #     # Show alert with commit comment on detecting possible performance regression
      #     alert-threshold: '200%'
      #     comment-on-alert: true
      #     fail-on-alert: false
      #     #alert-comment-cc-users: '@ktrz,@findmyway'
      #     gh-repository: 'github.com/benchmark-action/github-action-benchmark-results'
